brand_site/utils/db/models.py
from server import db


class BrandsData(db.Model):
    __tablename__ = "brands_data"
    id = db.Column(db.Integer, nullable=False, unique=True, primary_key=True, autoincrement=True)
    article = db.Column(db.String(64))
    title = db.Column(db.String(256))
    subtitle = db.Column(db.String(256))
    color = db.Column(db.String(64), nullable=True, default='')
    category = db.Column(db.String(128))
    materials = db.Column(db.String(1024), nullable=True, default='')
    details = db.Column(db.String(2048), nullable=True, default='')
    size_and_fit = db.Column(db.String(512), nullable=True, default='')
    description = db.Column(db.String(1024), nullable=True, default='')
    brand = db.Column(db.String(32))
    images = db.Column(db.JSON)


class AllBrands(db.Model):
    __tablename__ = "all_brands"
    id = db.Column(db.Integer, nullable=False, unique=True, primary_key=True, autoincrement=True)
    name = db.Column(db.String(32))
    short_name = db.Column(db.String(32))

brand_site/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__, template_folder='templates')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://oleg:oleg2000@localhost/parser_brands'
    db.init_app(app)

    from server.routes import app as server_app
    app.register_blueprint(server_app)

    with app.app_context():
        db.create_all()

    return app

brand_site/app.py
from server import create_app

app = create_app()


@app.template_filter()
def replace_n(value):
    return value.replace('\n', '<br />')


if __name__ == '__main__':
    app.run(host="0.0.0.0", port="5000")

brand_site/server/__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app():
    app = Flask(__name__, template_folder=f"{os.getcwd()}/templates", static_folder=f"{os.getcwd()}/static")
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://oleg:oleg2000@localhost/parser_brands'
    db.init_app(app)

    from .routes import app as server_app
    app.register_blueprint(server_app)

    with app.app_context():
        db.create_all()

    return app

brand_site/server/routes.py
import pandas as pd
from flask import Blueprint, render_template
from langdetect import LangDetectException
from server import db
from sqlalchemy import select
from utils.db.models import AllBrands, BrandsData

from brand_site.server.funcs import translator

app = Blueprint('server_app', __name__)


@app.route("/", methods=["GET"])
async def main_page():
    with db.engine.connect() as con:
        data = pd.read_sql_query(
            select(AllBrands.name, AllBrands.short_name).join(BrandsData,
                                                              AllBrands.short_name == BrandsData.brand).order_by(
                AllBrands.name).distinct(),
            con).to_dict('list')
    return render_template("main_page.html", brand=data, count=len(data['name']))


@app.route("/<brand>", methods=["GET"])
async def choice_category(brand):
    with db.engine.connect() as conn:
        data = pd.read_sql_query(select(BrandsData.category).where(BrandsData.brand == brand).distinct(), conn).to_dict(
            'list')
    return render_template("categories_page.html", data=data['category'], brand=brand)


@app.route("/<brand>/<category>")
async def choice_item(brand, category):
    with db.engine.connect() as conn:
        data = pd.read_sql_query(
            select(BrandsData).where(BrandsData.brand == brand).filter(BrandsData.category == category), conn).to_dict(
            'list')
    return render_template("items_page.html", data=data, brand=brand, category=category, count_records=len(data['id']))


@app.route("/<brand>/<category>/<article>")
async def item_detail(brand, category, article):
    from langdetect import detect
    with db.engine.connect() as conn:
        data = pd.read_sql_query(
            select(BrandsData).where(BrandsData.article == article).filter(
                BrandsData.category == category and BrandsData.brand == brand), conn
        ).to_dict('list')
    for i in range(len(data['id'])):
        try:
            if detect(data["subtitle"][i]) == "en":
                data["subtitle"][i] = await translator(data["subtitle"][i])
        except LangDetectException:
            pass
        try:
            if detect(data["materials"][i]) == "en":
                data["materials"][i] = await translator(data["materials"][i])
        except LangDetectException:
            pass
        try:
            if detect(data["details"][i]) == "en":
                data["details"][i] = await translator(data["details"][i])
        except LangDetectException:
            pass
        try:
            if detect(data["color"][i]) == "en":
                data["color"][i] = await translator(data["color"][i])
        except LangDetectException:
            pass
        try:
            if detect(data["description"][i]) == "en":
                data["description"][i] = await translator(data["color"][i])
        except LangDetectException:
            pass
    return render_template("item_page.html", data=data, count_records=len(data['id']))

brand_site/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% block title %}<title></title>{% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
{% block footer %}
{% endblock %}
</html>

brand_site/templates/categories_page.html
{% extends "base.html" %}
{% block title %}
    <title>Категории</title>
{% endblock %}
{% block content %}
    <div class="box">
        {% for category in data %}
            <div>
                <a href="{{ url_for('server_app.choice_item', brand=brand, category=category) }}">{{ category }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block footer %}
    <footer class="back_button">
        <a href="{{ url_for('server_app.main_page') }}">Назад</a>
    </footer>
{% endblock %}

brand_site/templates/item_page.html
{% extends "base.html" %}
{% block content %}
    <h1 class="title_h1">{{ data['category'][0] }}</h1>
    <div class="content">
        {% for i in range(count_records) %}
            <div class="top_content">
                <div class="left_panel">
                    <ul class="image_grid">
                        {% for photo in data['images'][i]['photos'] %}
                            <li class="image">
                                <div class="image-media">
                                    <div class="image-div">
                                        <img src="{{ photo | safe }}" alt="" width="">
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="right_panel">
                    <div class="title_subtitle-container">
                        <h1>
                            <span class="title">{{ data['title'][i] }}</span>
                            {% if data['subtitle'][i] %}
                                <span class="subtitle">{{ data['subtitle'][i] }}</span>
                            {% else %}
                                <span class="subtitle">{{ data['category'][i] }}</span>
                            {% endif %}
                            {% if data['color'][i] %}
                                <span class="subtitle">{{ data['color'][i] }}</span>
                            {% endif %}
                        </h1>
                        <p class="ref">Артикул: {{ data['article'][i] }}</p>
                    </div>
                    <div class="more_details_and_materials-container">
                        {% if data['details'][i] %}
                            <p class="size">
                                {{ data['details'][i] | replace_n | safe }}
                            </p>
                        {% endif %}
                        {% if data['materials'][i] %}
                            <p class="size"><br>
                                {{ data['materials'][i] | replace_n | safe }}</p>
                        {% endif %}
                        {% if data['description'][i] %}
                            <p class="size"><br>
                                {{ data['description'][i] | replace_n | safe }}</p>
                        {% endif %}
                        {% if data['size_and_fit'][i] %}
                            <p class="size"><br>
                                {{ data['size_and_fit'][i] | replace_n | safe }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block footer %}
    <footer class="back_button">
        <a href="{{ url_for('server_app.choice_item', brand=data['brand'][0], category=data['category'][0]) }}">Назад</a>
    </footer>
{% endblock %}

brand_site/templates/items_page.html
{% extends "base.html" %}
{% block content %}
    <h1 class="title_h1">{{ data['category'][0] }}</h1>
    <div class="content">
        <div class="item-list">
            {% for i in range(count_records) %}
                <a href="{{ url_for('server_app.item_detail', brand=data['brand'][i], category=data['category'][i], article=data['article'][i]) }}">
                    <div class="item_container">
                        <div class="item-img">
                            <img src="{{ data['images'][i]['photos'][0] | safe }}" alt="">
                        </div>
                    </div>
                    <div class="item-detail">
                        <div class="item-title">{{ data['title'][i] }}</div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %}
    <footer class="back_button">
        <a href="{{ url_for('server_app.choice_category', brand=brand) }}">Назад</a>
    </footer>
{% endblock %}

brand_site/templates/main_page.html
{% extends "base.html" %}
{% block title %}
    <title>Выбор бренда</title>
{% endblock %}
{% block content %}
    <div class="box">
        {% for i in range(count) %}
            <div>
                <a href="{{ url_for('server_app.choice_category', brand=brand['short_name'][i]) }}">{{ brand['name'][i] | upper }}</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}